default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: g2-rails-practice-kittens-development

test:
  <<: *default
  database: g2-rails-practice-kittens-test
